<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Mikrofine.HidExplorer</AssemblyName>
    <RootNamespace>Mikrofine.HidExplorer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.6.4" />
  </ItemGroup>
</Project>
